### PR TITLE
Add support for grafana plugins

### PR DESCRIPTION
**Pull request by sun77**
This change is [Reviewable](https://reviewable.io/reviews/criteo-forks/chef-grafana/1)

### CODE REVIEW

**Comment by jmauro** [comment]
_[libraries/plugin.rb, line 3 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2lwTLZNgoOMCcCgx:-KJf2lwVCRlNcp58YhQw:-1208027664) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L3)):_

> ``` Ruby
> module GrafanaCookbook
>   module Plugin
>     def manage_plugin(name, action='install')
> ```

self.manage_plugin

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
_[libraries/plugin.rb, line 7 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2hJwBKsDY0jvd_Xe:-KJf2hJxe9U8pH2DBiCD:641126979) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L7)):_

> ``` Ruby
>     end
> 
>     def plugin_available?(name)
> ```

use self.plug_available?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
_[libraries/plugin.rb, line 13 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2d6LY_dr6fzNIn9v:-KJf2d6MjPPrg3R6N4Xy:-1950139365) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L13)):_

> ``` Ruby
>     end
> 
>     def plugin_installed?(name)
> ```

Use self._plug_installed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
_[libraries/plugin.rb, line 19 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2YLxvqE9miNwIzW4:-KJf2YLysL0lum_6oVR1:1999589071) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L19)):_

> ``` Ruby
>     end
> 
>     def _build_cli_cmd(name, action)
> ```

Use self._build_cli_cmd

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by sun77** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[libraries/plugin.rb, line 3 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2lwTLZNgoOMCcCgx:-KJfl2UoqxcuHHJDvIVo:-230075843) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L3)):_
<details><summary>

<i>Previously, jmauro wrote…</i></summary>



> self.manage_plugin
> </details>
> I've added module_function

---

_[libraries/plugin.rb, line 7 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2hJwBKsDY0jvd_Xe:-KJflAIvV-SviUGjpBPZ:-230075843) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L7)):_
<details><summary>

<i>Previously, jmauro wrote…</i></summary>



> use self.plug_available?
> </details>
> I've added module_function

---

_[libraries/plugin.rb, line 13 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2d6LY_dr6fzNIn9v:-KJflBXd03aZCaXLEhPx:-230075843) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L13)):_
<details><summary>

<i>Previously, jmauro wrote…</i></summary>



> Use self._plug_installed?
> </details>
> I've added module_function

---

_[libraries/plugin.rb, line 19 [r1]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJf2YLxvqE9miNwIzW4:-KJflCi3nZsq580OnW8q:-230075843) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/87a127b08d9cba52ae7e4927bf38deddbc0da5d6/libraries/plugin.rb#L19)):_
<details><summary>

<i>Previously, jmauro wrote…</i></summary>



> Use self._build_cli_cmd
> </details>
> I've added module_function

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by iksaif** [comment]
Can you add some documentation / tests / example for this new code ?

<details><summary>

<i>Previously, sun77 (Anthony RABIER) wrote…</i></summary>



> #### Add support for grafana plugins
> 
> </details>

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[libraries/plugin.rb, line 12 [r2]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJiyNWKkobtISUIQMcW:-KJiyNWKkobtISUIQMcX:996200412) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/e73f2cae458f72533769ab05f7f8d250d6315f62/libraries/plugin.rb#L12)):_

> ``` Ruby
> 
>     def plugin_installed?(name)
>       cmd = Mixlib::ShellOut.new('/usr/sbin/grafana-cli plugins ls')
> ```

It's it always in /usr/sbin/ ? to we want to make this path an attribute ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-:-KJiyVx8e8SrAcZUrFvT:2053483331)_

**Comment by iksaif** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by sun77** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[libraries/plugin.rb, line 12 [r2]](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-KJiyNWKkobtISUIQMcW:-KJkaBkf0HjIWNJ2m2jw:-499146009) ([raw file](https://github.com/criteo-forks/chef-grafana/blob/e73f2cae458f72533769ab05f7f8d250d6315f62/libraries/plugin.rb#L12)):_
<details><summary>

<i>Previously, iksaif (Corentin Chary) wrote…</i></summary>



> It's it always in /usr/sbin/ ? to we want to make this path an attribute ?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
Reviewed 6 of 9 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by jmauro** [comment]
Serverspec? Why not `inspec`?

<details><summary>

<i>Previously, iksaif (Corentin Chary) wrote…</i></summary>



> Can you add some documentation / tests / example for this new code ?
> </details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-:-KJpA7PbjEBUJgPTs22a:-1915625418)_

**Comment by jmauro** [comment]
Reviewed 3 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1)_

**Comment by sun77** [comment]
Because it's a community cookbooks and they are using serverspec. 
So I won't change it for now.

<details><summary>

<i>Previously, jmauro wrote…</i></summary>



> Serverspec? Why not `inspec`?
> </details>

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-:-KJpAbgY1UdrBkZn0kJ1:1039563723)_

**Comment by iksaif** [comment]
:lgtm:

<details><summary>

<i>Previously, sun77 (Anthony RABIER) wrote…</i></summary>



> Because it's a community cookbooks and they are using serverspec. 
> So I won't change it for now.
> </details>

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/chef-grafana/1#-:-KJupemCmJQcxI_tSvoy:1417088721)_

**Pull request merged**
